const constants = require("../app/common/constants");
const const_env = require("./const_env");
const TABLE_NAME = require("./tablename").TABLE_NAME

module.exports = `
-- DROP DATABASE IF EXISTS \`##database_name##\`;
-- CREATE DATABASE IF NOT EXISTS \`##database_name##\` character set UTF8 collate utf8_bin;

-- use \`##database_name##\`;


CREATE TABLE IF NOT EXISTS ${TABLE_NAME.BENH_NHAN} (
  ID VARCHAR(20) PRIMARY KEY NOT NULL ,
  MA_BENH_NHAN VARCHAR(20) NOT NULL,
  MAT_KHAU VARCHAR(50),
  HO VARCHAR(10) NOT NULL,
  TEN text charset utf8mb4 NOT NULL,
  ANH_DAI_DIEN text,
  SO_DIEN_THOAI VARCHAR(20) NOT NULL,
  NGAY_SINH LONG,
  EMAIL TEXT,
  GIOI_TINH VARCHAR(10),
  MA_TINH_THANH VARCHAR(50),
  TEN_TINH_THANH VARCHAR(50),
  MA_QUAN_HUYEN VARCHAR(50),
  TEN_QUAN_HUYEN VARCHAR(50),
  MA_PHUONG_XA VARCHAR(50),
  TEN_PHUONG_XA VARCHAR(50),
  MA_KHU_VUC VARCHAR(10),
  DIA_CHI_CHI_TIET TEXT,
  MA_NGHE_NGHIEP TEXT,
  NGHE_NGHIEP VARCHAR(50),
  MA_DAN_TOC INT(5),
  DAN_TOC VARCHAR(50),
  MA_QUOC_TICH VARCHAR(50),
  QUOC_TICH VARCHAR(50),
  MA_BHXH VARCHAR(20),
  CMTND VARCHAR(20),
  CCCD VARCHAR(20),
  HO_CHIEU VARCHAR(20),
  BANG_LAI_XE VARCHAR(20),
  MA_VAN_HOA VARCHAR(20),
  VAN_HOA VARCHAR(50),
  MA_TON_GIAO VARCHAR(20),
  TON_GIAO VARCHAR(50),
  NOI_CONG_TAC TEXT,
  TIEN_SU_CA_NHAN TEXT,
  TIEN_SU_GIA_DINH TEXT,
  DI_UNG TEXT,
  BENH_VIEN_ID VARCHAR(50),
  PARTNER_CODE varchar(50),
  NOI_BAT boolean default false,
  NGAY_KHOI_TAO bigint,
  UNIQUE KEY MA_BENH_NHAN_no_duplicate (MA_BENH_NHAN, PARTNER_CODE)
);


`;
